name: "Bookcase"
author: "aimager"
markdown: kramdown
permalink: /:title.html
encoding: utf-8

# plugin
plugins:
  - jekyll-seo-tag

# custom
theme_name: "exhibit"
theme_dir: "theme"
layouts_dir: "_theme/exhibit/layouts"
includes_dir: "_theme/exhibit/layouts"
status: [读过, 想读]
footer: "<a href='http://blog.aimager.com'>blog</a>"
google-site-verfication: O_S8PGg7ST_LpvcgqqxqNVi-YhttDZ8gNoM1__BMQnE
baidu-site-verfication: lvkqTBHPbh
icon-path: "/aimager.png"

# array custom
collections:
  exhibit:
    output: true
  theme:
    output: true

exhibit_attrs:
  - index: author
    prefix: 作者
    type: tailor
  - index: publish_company
    prefix: 出版社
    type: tailor
  - index: publish_date
    prefix: 发行时间
    type: normal
  - index: publish_version
    prefix: 版本
    type: normal
  - index: tags
    prefix: 标签
    type: normal