#markdown: rdiscount
markdown: kramdown
# permalink: /:year/:month/:day/:title.html
permalink: /:title.html
name: "Library"

author: "aimager"
encoding: utf-8

footer: "| <a href='http://blog.aimager.com'>blog</a>"